-- Du lieu mau cho ban insert
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO movies
(title, genre, duration, release_date, summary, poster_url, status, is_now_showing)
VALUES
-- ======== PHIM ĐANG CHIẾU ========
('Ai Thương Ai Mến','Gia đình, Hài, Tâm lý',112,'2026-01-01','Câu chuyện gia đình nhiều thế hệ với những mâu thuẫn, yêu thương và sự gắn kết đầy cảm xúc.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565042/Ai_Th%C6%B0%C6%A1ng_Ai_M%E1%BA%BFn_w9yzhn.jpg','published',1),
('Tom & Jerry: Chiếc La Bàn Kỳ Bí','Gia đình, Hài, Hoạt hình, Phiêu lưu, Thần thoại',95,'2026-01-01','Tom và Jerry bước vào chuyến phiêu lưu kỳ ảo với chiếc la bàn bí ẩn mở ra những vùng đất huyền thoại.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565043/Tom_Jerry_Chi%E1%BA%BFc_La_B%C3%A0n_K%E1%BB%B3_B%C3%AD_obsaoi.jpg','published',1),
('Biệt Đội YOYO: Giải Cứu Giáng Sinh','Gia đình, Hoạt hình, Phiêu lưu',96,'2025-12-24','Biệt đội YOYO thực hiện nhiệm vụ giải cứu Giáng Sinh khỏi những âm mưu phá hoại bất ngờ.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565042/Bi%E1%BB%87t_%C4%90%E1%BB%99i_YOYO_Gi%E1%BA%A3i_C%E1%BB%A9u_Gi%C3%A1ng_Sinh_s9fnwk.jpg','published',1),
('Lạc Phàm Trần: Hậu Duệ Chúc Nữ','Hoạt hình, Khoa học viễn tưởng, Phiêu lưu',118,'2025-12-26','Hành trình kỳ ảo của những hậu duệ mang sứ mệnh bảo vệ thế giới giữa ranh giới thực và huyền ảo.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565042/L%E1%BA%A1c_Ph%C3%A0m_Tr%E1%BA%A7n_H%E1%BA%ADu_Du%E1%BB%87_Ch%C3%BAc_N%E1%BB%AF_yuyhqs.jpg','published',1),
('Phim Điện Ảnh Arrietty','Gia đình, Hoạt hình, Thần thoại',94,'2026-01-02','Cô bé tí hon Arrietty sống bí mật dưới sàn nhà và tình bạn đặc biệt với cậu bé loài người.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766566172/Phim_%C4%90i%E1%BB%87n_%E1%BA%A2nh_Arrietty_vbmyxh.jpg','published',1),
('Gia Đình Khủng Long: Mắc Kẹt Kỷ Jura','Gia đình, Hoạt hình',93,'2026-01-01','Một gia đình vô tình quay ngược thời gian và bị mắc kẹt giữa kỷ Jura đầy nguy hiểm.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565042/Gia_%C4%90%C3%ACnh_Kh%E1%BB%A7ng_Long_M%E1%BA%AFc_K%E1%BA%B9t_K%E1%BB%B7_Jura_vcyvrt.jpg','published',1),
('Bé Ghệ Ma Cưng','Hài, Tình cảm',125,'2026-01-09','Jo quay trở về tiệm quan cũ – nơi từng gắn liền với mối tình đặc biệt giữa anh và bé ma Anong. Trong hành trình đối diện với quá khứ, Jo dần bị cuốn vào vòng xoáy luân hồi, nơi anh có cơ hội chứng kiến những tiền kiếp mà mình và Anong từng cùng nhau trải qua. Dù thân phận và thời gian không ngừng đổi thay, sợi dây nhân duyên giữa họ vẫn bền chặt, dẫn dắt cả hai tìm lại tình yêu giữa ranh giới mong manh của người và ma.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766812168/B%C3%A9_gh%E1%BB%87_ma_c%C6%B0ng_pgtim2.jpg','published',1),
('Ác Linh Trùng Tang','Kinh dị',110,'2026-01-09','Sau nhiều năm xa cách, bốn anh chị em Jojo, Angga, Nindy và Momo trở về ngôi nhà cũ để gặp cha già và tưởng niệm em út Sofi – cô bé chết đuối bí ẩn khi còn nhỏ. Dù cố chôn giấu quá khứ, những sự kiện rùng rợn bắt đầu xảy ra khi sự thật dần bị khơi lại. Sofi, linh hồn mang đầy oán hận, trở về đòi lại công lý cho cái chết oan khuất của mình, buộc cả gia đình phải đối diện với tội lỗi mà họ từng che giấu suốt nhiều năm.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766812642/%C3%81c_Linh_Tr%C3%B9ng_Tang_zgylhm.jpg','published',1),
('Đại Ca Ha Ha Ha','Hài, Hành động',98,'2026-01-09','Soon Tae nuôi mộng mở chuỗi nhà hàng tiếng tăm nhưng bất đắc dĩ bị cuốn vào vai trò đại ca xã đoàn. Anh tìm cách trút bỏ trách nhiệm này cho Kang Pyo – cháu trai của một ông trùm quá cố, người lại mang giấc mơ trở thành vũ công tango và hoàn toàn không phù hợp với thế giới giang hồ. Trong khi đó, Pan Ho – kẻ chuyên gây rối – lại là người duy nhất tha thiết muốn làm đại ca nhưng chẳng ai tin tưởng. Những tình huống trớ trêu liên tiếp xảy ra, đẩy cả nhóm vào một “cuộc chiến né chức” đầy hài hước, nơi thua cược cũng chính là thắng cuộc.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766821457/%C4%90%E1%BA%A1i_Ca_Ha_Ha_Ha_f7ovo3.jpg','published',1),
('Thiên Đường Máu','Hành động, Tâm lý',113,'2025-12-31','Thiên Đường Máu là bộ phim điện ảnh Việt Nam khai thác đề tài nạn lừa đảo đưa người Việt ra nước ngoài bằng những lời hứa việc nhẹ lương cao. Nhiều nạn nhân bị đưa đến các “đặc khu”, nơi họ phải sống trong cảnh giam lỏng, bị ép buộc tham gia các đường dây lừa đảo và gọi điện chiếm đoạt chính đồng bào của mình. Giữa địa ngục trần gian ấy, một số người đã liều mình tìm cách trốn thoát, phơi bày sự thật tàn khốc phía sau giấc mộng đổi đời.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766821602/THI%C3%8AN_%C4%90%C6%AF%E1%BB%9CNG_M%C3%81U_mxtixk.jpg','published',1),

-- ======== PHIM SẮP CHIẾU ========
('Chuột Nhí Siêu Tốc Độ','Hoạt hình, Phiêu lưu, Gia đình',98,'2026-01-23','Chuột Nhí sở hữu khả năng chạy nhanh siêu tốc và bước vào hành trình bảo vệ bạn bè.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766809321/Chu%E1%BB%99t_Nh%C3%AD_Si%C3%AAu_T%E1%BB%91c_%C4%90%E1%BB%99_bes2fv.jpg','published',0),
('5 Centimet Trên Giây live action','Tâm lý, Tình cảm',121,'2026-01-16','Phiên bản người đóng kể về khoảng cách, thời gian và những mối tình không trọn vẹn.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766822429/5_Centimet_Tr%C3%AAn_Gi%C3%A2y_live_action_ewweut.jpg','published',0),
('Báu Vật Trời Cho','Gia đình, Tâm lý',120,'2026-02-17','Câu chuyện cảm động về một gia đình và những giá trị tình thân đáng quý.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565041/B%C3%A1u_V%E1%BA%ADt_Tr%E1%BB%9Di_Cho_ua2ems.jpg','published',0),
('Nhà Ba Tôi Một Phòng','Gia đình, Hài, Tâm lý',110,'2026-02-17','Câu chuyện gia đình ấm áp, hài hước và đầy cảm xúc xoay quanh ba và con.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766809287/Nh%C3%A0_Ba_T%C3%B4i_M%E1%BB%99t_Ph%C3%B2ng_lzxtpo.jpg','published',0),
('Mùi Phở','Gia đình, Ẩm thực, Tâm lý',105,'2026-02-17','Câu chuyện nhẹ nhàng về gia đình nhiều thế hệ gắn bó với nghề nấu phở truyền thống.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565042/M%C3%B9i_Ph%E1%BB%9F_n79e9e.jpg','published',0),
('Thoát Khỏi Tận Thế','Khoa học viễn tưởng, Phiêu lưu',118,'2026-03-20','Cuộc chạy đua sinh tồn khi thảm họa toàn cầu cận kề và mọi người tìm đường thoát hiểm.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766565043/Tho%C3%A1t_Kh%E1%BB%8Fi_T%E1%BA%ADn_Th%E1%BA%BF_c2taet.jpg','published',0),
('Tài','Gia đình, Hài, Hành động, Tâm lý',120,'2026-03-01','Tài đã trải qua một hành trình đầy khó khăn, làm đủ mọi nghề, thậm chí dấn thân vào những phi vụ nguy hiểm, đặt cược cả mạng sống để bảo vệ thứ tài sản quý giá nhất của đời mình. Đứng trước những nghịch cảnh khắc nghiệt và lựa chọn sinh tử, Tài buộc phải đối diện với chính bản thân để tìm ra nghị lực vươn lên. Bộ phim mang đến những khoảnh khắc vừa hài hước vừa xúc động, khắc họa sâu sắc tình thân, tình yêu và sự bao dung trong các mối quan hệ gia đình và xã hội.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766813341/TAI_ftjhou.jpg','published',0),
('Công Chúa Mononoke','Hoạt hình, Phiêu lưu, Thần thoại',134,'2026-01-09','Ashitaka, một chàng trai trẻ sống tại ngôi làng Emishi, bị trúng lời nguyền chết người sau khi tiêu diệt một vị thần quỷ. Để tìm cách hóa giải lời nguyền, anh lên đường đến vùng đất phía tây, nơi đang diễn ra cuộc xung đột dữ dội giữa con người và các vị thần rừng. Tại đây, Ashitaka gặp San – cô bé được Thần Sói Moro nuôi dưỡng – và dần bị cuốn vào cuộc chiến giữa thiên nhiên và lòng tham của con người. Bộ phim là hành trình tìm kiếm sự cân bằng, nơi con người và thiên nhiên buộc phải đối diện với hậu quả từ chính lựa chọn của mình.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766813936/PHIM_%C4%90I%E1%BB%86N_%E1%BA%A2NH_C%C3%94NG_CH%C3%9AA_MONONOKE_oh1yqh.jpg','published',0),
('Phim Super Mario Thiên Hà','Hài, Hành động, Hoạt hình',100,'2026-04-03','Phim Super Mario Thiên Hà là bộ phim hoạt hình lấy bối cảnh trong thế giới của Anh Em Super Mario, tiếp nối thành công của Phim Anh Em Super Mario (2023). Mario cùng những người bạn bước vào một cuộc phiêu lưu hoàn toàn mới, đối mặt với các thử thách nguy hiểm và kẻ thù quen thuộc trong hành trình bảo vệ Vương quốc Nấm. Bộ phim mang đến những pha hành động sôi động, yếu tố hài hước đặc trưng và tinh thần phiêu lưu đậm chất Mario, hứa hẹn chinh phục khán giả ở mọi lứa tuổi.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766814685/PHIM_SUPER_MARIO_THI%C3%8AN_H%C3%80_nd3y1h.jpg','published',0),
('Chàng Mèo Mang Mũ','Gia đình, Hài, Hoạt hình, Phiêu lưu',95,'2026-11-06','Chàng Mèo Mang Mũ là câu chuyện phiêu lưu hài hước xoay quanh chú mèo tinh nghịch với chiếc mũ đặc trưng, người luôn mang đến những rắc rối ngoài sức tưởng tượng. Trong một nhiệm vụ mới đầy thử thách, chú mèo đồng hành cùng hai anh em Gabby và Sebastian, đối mặt với hàng loạt tình huống oái oăm và bài học về trách nhiệm, tình bạn và sự trưởng thành. Bộ phim mang màu sắc vui nhộn, phù hợp cho cả gia đình.','https://res.cloudinary.com/doo2wxwzv/image/upload/v1766822115/Ch%C3%A0ng_M%C3%A8o_Mang_M%C5%A9_kyezuf.jpg','published',0);

SET FOREIGN_KEY_CHECKS = 1;
